spring:
  config:
    import: "classpath:key.yml"
  elasticsearch:
    rest:
      uris: ${instance}
      username: ${instanceUN}
      password: ${instancePW}
  data:
    elasticsearch:
      repositories:
        enabled: false



###deploy test
###deploy test 2
###deploy test 3
###deploy test 4
###deploy test
###deploy test 2
###deploy test 3
###deploy test 4
###deploy test
###deploy test 2
###deploy test 3
###deploy test 4
